sudo: required
dist: trusty
services: docker

jobs:
  include:
    - stage: build dependencies (ubuntu-xenial)
      os: linux
      env:
      - PROTOBUF_VER=3.4.1
      - GRPCIO_VER=1.7.0
      - PLATFORM=ubuntu-xenial
      script: "./build.sh"
    - stage: build dependencies (debian-stretch)
      os: linux
      env:
      - PROTOBUF_VER=3.4.1
      - GRPCIO_VER=1.7.0
      - PLATFORM=debian-stretch
      script: "./build.sh"

  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master