sudo: required
dist: trusty
services: docker

jobs:
  include:
    - stage: build dependencies
      os: linux
      env:
      - BUILD_DIR='/build'
      - PROTOBUF_VER=3.4.1
      - GRPCIO_VER=1.7.0
      script: "./build.sh"
