sudo: required
dist: trusty
services: docker
jobs:
  include:
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=xenial
    script: 
    - "./travis_build.sh"
    - "./push_to_git.sh"
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=stretch
    script:
    - "./travis_build.sh"
    - "./push_to_git.sh"
  - stage: merge buildfiles from architectures to a single Git branch
    os: linux
    env:
    script: "./merge_git.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_12e7435d0bba_key -iv $encrypted_12e7435d0bba_iv
  -in keys.tar.enc -out keys.tar -d
